
name: Windows

on: [push, pull_request]

permissions:
  contents: read

jobs:
  Build:
    name: Basic
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v3

    - name: Install requirements
      run: |
          choco install make 
          choco install qt5-default

    - name: Build on windows
      run: |
          deploy\build_windows.bat
